name: film
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  http: ^0.12.2
  animated_text_kit: ^3.1.0
  webview_flutter: ^1.0.7
  flutter_spinkit: ^4.1.2+1
  share: ^0.6.5+4
  launch_review: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf

  assets:
    - images/youtube.png